# -*- mode: ruby -*-
# vi: set ft=ruby :

system("
    if [ #{ARGV[0]} = 'up' ] || [ #{ARGV[0]} = 'provision' ]; then
        ansible-galaxy install -f -i -p roles -r requirements.yml
    fi
")

Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
  config.vm.box = "centos65"
  config.vm.box_url = "http://downloads.juwai.io/devops/boxes/centos65-x86-64.box"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
  end
end
